spring.application.name=battleship-api
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d7kb3c1f9bms73aaop60-a.frankfurt-postgres.render.com:5432/battleship_db_v2
spring.datasource.username=battleship_db_v2_user
spring.datasource.password=GyzaV8SsJOPVf9AHqRv2aTTJXjolCyu0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb+srv://spook242:Mon0242gO!@cluster0.jn2zcy4.mongodb.net/battleship_game?appName=Cluster0

security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
security.jwt.expiration-time=86400000